// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image10":
            case "myImage1":return img`
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
. . . . . . . . . . . 
`;
            case "image1":
            case "bg_0":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffff111111111dddddbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1f11f1fff11ff111ff1ff1fcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1f1f1f1f1f11f1ff1f1ff1fcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1f1f1f1f11fff1ff1f1ff1fcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1f1fff1ff111f1ff1ff111fcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffff111ddddddbbbbbbcccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image12":
            case "myImage2":return img`
f f f f f f f f f f f f f f f f 
f 9 9 9 9 9 6 6 6 6 6 6 6 8 8 f 
f 9 f f f f f f f f f f f f 8 f 
f 9 f 6 6 6 6 6 6 6 6 6 6 f 8 f 
f 6 f 6 6 8 8 8 8 6 6 6 6 f 8 f 
f 6 f 6 6 6 8 8 8 8 6 6 6 f c f 
f 6 f 6 6 6 6 8 8 8 c 6 6 f c f 
f 8 f 6 6 6 6 8 8 8 c 6 6 f c f 
f 8 f 6 6 6 8 8 8 c 6 6 6 f c f 
f 8 f 6 6 c c c c 6 6 6 6 f c f 
f 8 f 6 6 6 6 6 6 6 6 6 6 f c f 
f 8 f f f f f f f f f f f f c f 
f 8 f f f f f f f f f f f f c f 
f 8 8 c c c c c c c c c c c c f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`;
            case "image11":
            case "myImage0":return img`
f f f f f f f f f f f f f f f f 
f 1 1 1 1 1 9 9 9 9 9 9 9 6 6 f 
f 1 f f f f f f f f f f f f 6 f 
f 1 f 9 9 9 9 9 9 9 9 9 9 f 6 f 
f 9 f 9 9 6 6 6 6 9 9 9 9 f 6 f 
f 9 f 9 9 9 6 6 6 6 9 9 9 f 8 f 
f 9 f 9 9 9 9 6 6 6 8 9 9 f 8 f 
f 6 f 9 9 9 9 6 6 6 8 9 9 f 8 f 
f 6 f 9 9 9 6 6 6 8 9 9 9 f 8 f 
f 6 f 9 9 8 8 8 8 9 9 9 9 f 8 f 
f 6 f 9 9 9 9 9 9 9 9 9 9 f 8 f 
f 6 f f f f f f f f f f f f 8 f 
f 6 f f f f f f f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 8 8 8 8 8 8 f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`;
            case "image3":
            case "myImage3":return img`
. . 1 1 1 9 9 9 . . . . 
. 1 f f f f f f 9 . . . 
1 f 1 1 1 9 9 6 f 9 . . 
1 f 1 f f f 6 6 f 9 . . 
9 f 1 f f 6 f f 6 . . . 
9 f 9 f 6 f 6 f 6 . . . 
6 f 9 6 f 6 . . . . . . 
6 f 6 6 f f . . . . . . 
. 6 f f 6 6 . . . . . . 
. . 6 6 . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
`;
            case "image4":
            case "myImage4":return img`
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . . . . . . . 
. . . . . . f 8 f 8 . . 
. . . . . . 8 f 8 f 8 . 
. . . . . . f 8 f 8 f 8 
. . . . . . 8 f 8 8 f 8 
. . . . . . . 8 f f 8 . 
. . . . . . . . 8 8 . . 
`;
            case "image2":
            case "myImage":return img`
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . f 8 f . . 
. . . . . 8 f 8 f . 
. . . . . f 8 f 8 f 
. . . . . . f 8 8 f 
. . . . . . . f f . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim3":return [img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
55...........................96.
54...........................66.
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............................32..
............................22..
................................
79..............................
77..............................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
555.........................96..
.54.........................666.
.55.............................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...........................32...
...........................222..
.7..............................
779.............................
.77.............................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...5........................6...
.555.......................96...
..54.......................666..
..55............................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........................322...
..........................222...
...........................2....
..7.............................
.779............................
..777...........................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
....5...........................
..555.....................6.....
...54....................96.....
...55....................666....
................................
................................
................................
................................
................................
................................
................................
................................
.........................322....
.........................222....
..........................2.....
....7...........................
...779..........................
....777.........................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
......5.........................
....555................666......
.....545...............96.......
.....55................66.......
................................
................................
................................
................................
................................
.......................2........
.......................322......
.......................22.......
........................2.......
......77........................
.....779........................
......777.......................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.......5...........666..........
.....555...........96...........
......545..........66...........
......55........................
................................
................................
....................2...........
....................322.........
....................22..........
.....................2..........
........77......................
.......779......................
........777.....................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..........5......666............
........555......96.............
.........545.....66.............
.........55.....................
.................2..............
.................322............
...........77....22.............
..........779.....2.............
...........777..................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............666...............
............5.96................
..........555.662...............
...........5457.322.............
...........5579.22..............
.............777.2..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.............2....7.............
............2322.79.............
.............22..777............
................................
...........666..................
...........96...................
...........66...5...............
..............555...............
...............545..............
...............55...............
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...................7............
...........2......79............
..........2322....777...........
...........22...................
................................
................................
................................
.........666....................
.........96........5............
.........66......555............
..................545...........
..................55............
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
....................7...........
...........2.......79...........
..........2322.....777..........
...........22...................
................................
................................
................................
................................
................................
.........666........5...........
.........96.......555...........
.........66........545..........
...................55...........
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..................7.............
...........2.....79.............
..........2322...777............
...........22...................
................................
................................
................................
...........666......5...........
...........96.....555...........
...........66......545..........
...................55...........
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.................7..............
............2...79..............
...........2322.777.............
............22..................
................................
............666...5.............
............96..555.............
............66...545............
.................55.............
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.............2...7..............
............232279..............
.............22.777.............
.............666.5..............
.............96555..............
.............66.545.............
................55..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............32.9..6.............
...........12227776.............
...........22227776.............
...........29625774.............
...........96685554.............
...........66685554.............
...........6..8.55..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
............222.................
...........212227...6...........
...........22222717776..........
..........22222.777776..........
..........22..2.77776...........
...........666..5.774...........
..........61668.1555............
..........66668.55554...........
.........66668..55554...........
.........66..8...554............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
............222.................
...........21222.77..6..........
...........22222.17776..........
..........22222.777776..........
..........22222.77776...........
.........22222.77776............
.........22..2.77776............
..........666...776.............
.........61668.55..4............
.........66668.15554............
........66668.555554............
........66668.55554.............
.......66668.55554..............
.......66..8.55554..............
..............554...............
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
................................
...........3333.................
..........31222b.99...6.........
..........32222b.179996.........
..........32222b.977776.........
.........32222b.977776..........
.........32222b.977776..........
.........32222b.977776..........
........32222b.977776...........
........32bbbb.977776...........
........3b...b.977776...........
.........9999...6666............
........916668.dd...4...........
........966668.15ddd4...........
........966668.d55554...........
.......966668.d55554............
.......966668.d55554............
.......966668.d55554............
......966668.d55554.............
......968888.d55554.............
......98...8.d55554.............
..............4444..............
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
...........aaaa.................
........aaa1222aa..6......6.....
.......a1122222ca.6766666686....
.......a3222222ca.6797777786....
.......a2222222ca.6177777786....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
.....a2222222ca.6777777786......
.....a2222222ca.6777777786......
.....a2aaaaaaca.6777777786......
......a......a..667777666.......
........8888......6666..........
.....888166688..4......4........
....81696666c8.45444444e4.......
....86666666c8.45155555e4.......
....86666666c8.4d555555e4.......
...81666666c8.45555555e4........
...86666666c8.45555555e4........
...86666666c8.45555555e4........
..86666666c8.45555555e4.........
..86666666c8.45555555e4.........
..86888888c8.45555555e4.........
...8......8..445555444..........
...............4444.............
................................
................................
................................
................................
`];
            case "anim4":return [img`
................................
................................
................................
...........aaaa.................
........aaa1222aa..6......6.....
.......a1122222ca.6766666686....
.......a3222222ca.6797777786....
.......a2222222ca.6177777786....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
.....a2222222ca.6777777786......
.....a2222222ca.6777777786......
.....a2aaaaaaca.6777777786......
......a......a..667777666.......
........8888......6666..........
.....888166688..4......4........
....81696666c8.45444444e4.......
....86666666c8.45155555e4.......
....86666666c8.4d555555e4.......
...81666666c8.45555555e4........
...86666666c8.45555555e4........
...86666666c8.45555555e4........
..86666666c8.45555555e4.........
..86666666c8.45555555e4.........
..86888888c8.45555555e4.........
...8......8..445555444..........
...............4444.............
................................
................................
................................
................................
`, img`
................................
................................
...........2222.................
........222aaaa22..7......7.....
.......2aaa1222aa27677777767....
......2a1122222ca267666666867...
......2a3222222ca267977777867...
......2a2222222ca261777777867...
.....2a2222222ca267777777867....
.....2a2222222ca267777777867....
.....2a2222222ca267777777867....
....2a2222222ca267777777867.....
....2a2222222ca267777777867.....
....2a2aaaaaaca267777777867.....
.....2a222222a276677776667......
.....626888862..776666777.......
....688816668865417777545.......
...681696666c8545444444e45......
...686666666c8545155555e45......
...686666666c854d555555e45......
..681666666c8545555555e45.......
..686666666c8545555555e45.......
..686666666c8545555555e45.......
.686666666c8545555555e45........
.686666666c8545555555e45........
.686888888c8545555555e45........
..686666668654455554445.........
...6......6..554444555..........
...............5555.............
................................
................................
................................
`, img`
................................
................................
...........2222.................
........222aaaa22..7......7.....
.......2aaa1222aa27677777767....
......2a1122222ca267666666867...
......2a3222222ca267977777867...
......2a2222222ca261777777867...
.....2a2222222ca267777777867....
.....2a2222222ca267777777867....
.....2a2222222ca267777777867....
....2a2222222ca267777777867.....
....2a2222222ca267777777867.....
....2a2aaaaaaca267777777867.....
.....2a222222a276677776667......
.....626888862..776666777.......
....688816668865417777545.......
...681696666c8545444444e45......
...686666666c8545155555e45......
...686666666c854d555555e45......
..681666666c8545555555e45.......
..686666666c8545555555e45.......
..686666666c8545555555e45.......
.686666666c8545555555e45........
.686666666c8545555555e45........
.686888888c8545555555e45........
..686666668654455554445.........
...6......6..554444555..........
...............5555.............
................................
................................
................................
`, img`
................................
................................
................................
...........aaaa.................
........aaa1222aa..6......6.....
.......a1122222ca.6766666686....
.......a3222222ca.6797777786....
.......a2222222ca.6177777786....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
......a2222222ca.6777777786.....
.....a2222222ca.6777777786......
.....a2222222ca.6777777786......
.....a2aaaaaaca.6777777786......
......a......a..667777666.......
........8888......6666..........
.....888166688..4......4........
....81696666c8.45444444e4.......
....86666666c8.45155555e4.......
....86666666c8.4d555555e4.......
...81666666c8.45555555e4........
...86666666c8.45555555e4........
...86666666c8.45555555e4........
..86666666c8.45555555e4.........
..86666666c8.45555555e4.........
..86888888c8.45555555e4.........
...8......8..445555444..........
...............4444.............
................................
................................
................................
................................
`];
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . f . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
f f f f f f f f f f 
f 9 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 9 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 9 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 1 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 1 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 9 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 9 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 9 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 9 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 9 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 9 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 9 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 9 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 9 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 9 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 9 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 9 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 9 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 9 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 9 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 9 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 9 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 9 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 1 f f f f f f 6 f 
f 1 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`, img`
f f f f f f f f f f 
f 1 1 1 9 9 6 6 6 f 
f 9 f f f f f f 6 f 
f 9 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f . . . . f 8 f 
f 6 f f f f f f 8 f 
f 6 6 8 8 8 8 8 8 f 
f f f f f f f f f f 
f f f f f f f f f f 
`];
            case "myAnim1":
            case "anim5":return [img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 9 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 9 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 9 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 9 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 1 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 1 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 1 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 1 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 9 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 9 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 9 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 9 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 9 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 1 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 1 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 1 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 1 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 1 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 1 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 1 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 1 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 1 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 1 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 1 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 1 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 1 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 1 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 1 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 1 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 1 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 1 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 1 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 1 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 1 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 1 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 1 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 1 f f f f f f f f f f 6 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`, img`
. . . . . . . . . . . . . . . . 
. f f f f f f f f f f f f f f . 
. f 1 1 1 1 9 9 9 9 6 6 6 6 f . 
. f 9 f f f f f f f f f f 6 f . 
. f 1 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 9 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f . . . . . . . . f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 f f f f f f f f f f 8 f . 
. f 6 6 6 6 6 6 8 8 8 8 8 8 f . 
. f f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f f . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
